# Generated by Django 5.2.17 on 2026-09-11 19:13

import django.db.models.deletion
import presentations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva')], default='active', max_length=20)),
                ('token', models.CharField(default=presentations.models.generate_presentation_token, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presentación',
                'verbose_name_plural': 'Presentaciones',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=presentations.models.media_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video'), ('document', 'Documento')], max_length=20)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('presentation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='presentations.presentation')),
            ],
            options={
                'verbose_name': 'Archivo multimedia',
                'verbose_name_plural': 'Archivos multimedia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('slide_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('video', 'Video'), ('mixed', 'Mixta')], default='text', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Subtítulo')),
                ('content', models.TextField(blank=True, verbose_name='Contenido')),
                ('duration', models.PositiveIntegerField(default=10, verbose_name='Duración (segundos)')),
                ('background_color', models.CharField(default='#1a1a2e', max_length=7, verbose_name='Color de fondo')),
                ('custom_content', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_slides', to='presentations.mediaasset')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_slides', to='presentations.mediaasset')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='presentations.presentation')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_slides', to='presentations.mediaasset')),
            ],
            options={
                'verbose_name': 'Diapositiva',
                'verbose_name_plural': 'Diapositivas',
                'ordering': ['order', 'id'],
            },
        ),
    ]
