# Generated by Django 5.2.17 on 2026-09-11 19:35

import django.db.models.deletion
import presentations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='True si el archivo fue generado por importación PowerPoint'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('powerpoint', 'PowerPoint')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='PowerPointImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to=presentations.models.powerpoint_original_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completada'), ('failed', 'Fallida')], default='pending', max_length=20)),
                ('slide_count', models.PositiveIntegerField(default=0)),
                ('processed_slide_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='powerpoint_imports', to=settings.AUTH_USER_MODEL)),
                ('presentation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='powerpoint_import', to='presentations.presentation')),
            ],
            options={
                'verbose_name': 'Importación PowerPoint',
                'verbose_name_plural': 'Importaciones PowerPoint',
                'ordering': ['-created_at'],
            },
        ),
    ]
