# Generated by Django 5.2.17 on 2026-09-11 19:13

import django.db.models.deletion
import screens.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('identifier', models.CharField(default=screens.models.generate_screen_identifier, editable=False, max_length=32, unique=True)),
                ('pairing_code', models.CharField(blank=True, default=screens.models.generate_pairing_code, help_text='Código para vincular la pantalla (Fase 2)', max_length=16)),
                ('status', models.CharField(choices=[('connected', 'Conectada'), ('disconnected', 'Desconectada'), ('pending', 'Pendiente de vinculación')], default='pending', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_presentation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screens', to='presentations.presentation')),
            ],
            options={
                'verbose_name': 'Pantalla',
                'verbose_name_plural': 'Pantallas',
                'ordering': ['name'],
            },
        ),
    ]
