# Generated by Django 5.2.17 on 2026-09-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='reload_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screen',
            name='reload_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
