# Generated by Django 5.2.17 on 2026-09-11 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presentations', '0001_initial'),
        ('screens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('presentation_created', 'Presentación creada'), ('presentation_updated', 'Presentación modificada'), ('presentation_deleted', 'Presentación eliminada'), ('presentation_duplicated', 'Presentación duplicada'), ('presentation_toggled', 'Estado de presentación cambiado'), ('slide_created', 'Diapositiva creada'), ('slide_updated', 'Diapositiva modificada'), ('slide_deleted', 'Diapositiva eliminada'), ('slide_reordered', 'Diapositivas reordenadas'), ('screen_connected', 'Pantalla conectada'), ('screen_disconnected', 'Pantalla desconectada'), ('screen_presentation_changed', 'Cambio de presentación en pantalla')], max_length=50)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('presentation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='presentations.presentation')),
                ('screen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='screens.screen')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de evento',
                'verbose_name_plural': 'Registros de eventos',
                'ordering': ['-created_at'],
            },
        ),
    ]
