# Generated by Django 5.2.17 on 2026-09-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo del sitio')),
                ('login_logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo de login')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Favicon')),
                ('site_name', models.CharField(default='Cloud Screen', max_length=100, verbose_name='Nombre del sitio')),
                ('browser_title', models.CharField(default='Cloud Screen', max_length=100, verbose_name='Título del navegador')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(choices=[('presentation_created', 'Presentación creada'), ('presentation_updated', 'Presentación modificada'), ('presentation_deleted', 'Presentación eliminada'), ('presentation_duplicated', 'Presentación duplicada'), ('presentation_toggled', 'Estado de presentación cambiado'), ('presentation_imported', 'Presentación importada desde PowerPoint'), ('presentation_import_failed', 'Error al importar PowerPoint'), ('slide_created', 'Diapositiva creada'), ('slide_updated', 'Diapositiva modificada'), ('slide_deleted', 'Diapositiva eliminada'), ('slide_reordered', 'Diapositivas reordenadas'), ('screen_connected', 'Pantalla conectada'), ('screen_disconnected', 'Pantalla desconectada'), ('screen_presentation_changed', 'Cambio de presentación en pantalla')], max_length=50),
        ),
    ]
