# Generated by Django 5.2.17 on 2026-09-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_alter_eventlog_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='login_logo_width',
            field=models.IntegerField(default=200, verbose_name='Ancho del logo en login (px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sidebar_logo_width',
            field=models.IntegerField(default=120, verbose_name='Ancho del logo en el sidebar (px)'),
        ),
    ]
